### ISSUE TITLE
benchmark shows that dprint-node is just a bit faster

### ISSUE THREAD

**Issue by tuananh** [devongovett/dprint-node#2]
manjaro linux, node 16.2.0 (latest)

```
prettier 213.61 opts/sec (mean: 4.682ms, stddev: 6.011ms, 50 samples)
dprint 264.2 opts/sec (mean: 3.785ms, stddev: 0.223ms, 50 samples)
```

![image](https://user-images.githubusercontent.com/627278/120655732-2b504800-c4ad-11eb-8505-7ef0197cb7b4.png)

any idea what could have cause that?

**Comment by IWANABETHATGUY** [comment]
1. js is not much slower than rust after jit.
2. dprint-node has huge overhead when serialize and deserialize your code.

**Comment by tuananh** [comment]
@IWANABETHATGUY the number seems off. it's so different from the benchmark from the readme

```
prettier 216.33 opts/sec (mean: 4.623ms, stddev: 6.7ms, 50 samples)
dprint 6,694.02 opts/sec (mean: 0.149ms, stddev: 0.094ms, 50 samples)
```

**Comment by dsherret** [comment]
I get this on windows:

```
> node bench.js
prettier 238.19 opts/sec (mean: 4.198ms, stddev: 6.05ms, 50 samples)
dprint 6,020.03 opts/sec (mean: 0.166ms, stddev: 0.075ms, 50 samples)
```

Then in WSL (ubuntu):

```
$ node bench.js
prettier 238.9 opts/sec (mean: 4.186ms, stddev: 6.185ms, 50 samples)
dprint 7,141.94 opts/sec (mean: 0.14ms, stddev: 0.105ms, 50 samples)
```

Overall dprint-plugin-typescript is much faster than prettier in the majority of cases (it usually finishes before babel within prettier even finishes parsing an AST) though the "preferSingleLine" config is not up to par with prettier yet in terms of stability.

I don't think the overhead of sending the data to rust should be that much in comparison to the work being done for formatting. There's probably something else going on here.

**Comment by dsherret** [comment]
@tuananh how did you build it? Did you build with `yarn build` or `yarn build-release`?

**Comment by tuananh** [comment]
Just do `npm run build` and then `node bench.js`

**Comment by dsherret** [comment]
@tuananh ok cool. Try `npm run build-release` instead. `npm run build` will build a debug build, which will be considerably slower.

**Comment by IWANABETHATGUY** [comment]
@dsherret, you're right. But the overhead will become larger with the file size incresizing.
use default small-js, bench result is below: 
```
prettier 201.26 opts/sec (mean: 4.969ms, stddev: 6.969ms, 50 samples)
dprint 5,407.74 opts/sec (mean: 0.185ms, stddev: 0.096ms, 50 samples)
```
dprint is 27 times faster than prettier.
try to use a bigger js file https://github.com/acornjs/acorn/blob/master/acorn/src/tokenize.js,
```
prettier 12.41 opts/sec (mean: 80.583ms, stddev: 44.753ms, 50 samples)
dprint 97.65 opts/sec (mean: 10.241ms, stddev: 1.873ms, 50 samples)
```
dprint is 8 times faster than prettier

**Comment by dsherret** [comment]
@IWANABETHATGUY I agree, but don't think we can say much about the impact without seeing a measurement of the time it takes to pass the data back and forth in comparison with the overall time. It may just be that dprint is slower for that file. I've usually found dprint natively to be about 10x faster on average, but sometimes it may only be 2x. It may actually even be slower than prettier when looking at minified files as dprint-plugin-typescript currently isn't optimized for that (wouldn't be too much work to get it faster though).

**Comment by IWANABETHATGUY** [comment]
@dsherret agree. my mistake
